// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCE3dIGuKIKaqZL4ZAg8sSqcSrW_Hw8Q',
    appId: '1:941887680259:web:3357eba3e9adc304690336',
    messagingSenderId: '941887680259',
    projectId: 'turmalina-auth',
    authDomain: 'turmalina-auth.firebaseapp.com',
    storageBucket: 'turmalina-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVbql3SGZOI3cf6Zf6nBxyK7b0-UKjKk',
    appId: '1:941887680259:android:66c974bfa6c66987690336',
    messagingSenderId: '941887680259',
    projectId: 'turmalina-auth',
    storageBucket: 'turmalina-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxPw7DQWleVTKcqab506LW9wwpsTGSCWU',
    appId: '1:941887680259:ios:a9f6e077bc24e30c690336',
    messagingSenderId: '941887680259',
    projectId: 'turmalina-auth',
    storageBucket: 'turmalina-auth.firebasestorage.app',
    iosBundleId: 'com.example.turmalina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxPw7DQWleVTKcqab506LW9wwpsTGSCWU',
    appId: '1:941887680259:ios:a9f6e077bc24e30c690336',
    messagingSenderId: '941887680259',
    projectId: 'turmalina-auth',
    storageBucket: 'turmalina-auth.firebasestorage.app',
    iosBundleId: 'com.example.turmalina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrCE3dIGuKIKaqZL4ZAg8sSqcSrW_Hw8Q',
    appId: '1:941887680259:web:cf7f32da61294fc9690336',
    messagingSenderId: '941887680259',
    projectId: 'turmalina-auth',
    authDomain: 'turmalina-auth.firebaseapp.com',
    storageBucket: 'turmalina-auth.firebasestorage.app',
  );

}